### PR TITLE
Use GCC_VERSION for filtering gcc>9

### PR DESCRIPTION
**Pull request by montjoie**
Instead of having multiple patch for each gcc, gcc filtering could be
done directly in Kconfig.

This patch adds gcc conds for options needing gcc>9.

Closes: #61

Signed-off-by: Corentin Labbe <clabbe.montjoie@gmail.com>

### CODE REVIEW

**Comment by montjoie** [comment]
Perhaps PR need to remove the 2 other patch. and rename the file ?

**Comment by graysky2** [comment]
Thanks for drafting the PR.  When I try to apply this to 5.11.10, `patch` throws an error.  Do you see this on your side?
```
patching file arch/x86/Kconfig.cpu
patch: **** malformed patch at line 226:  	depends on X86_32
```

**Comment by montjoie** [comment]
Yes I got this also. Sorry I didnt try to apply back.
I have git format-patch then copied other the resulting patch.
Then I have filtered unrelated changes but it seems I have too filtered.

let me fix it and test more.

**Comment by montjoie** [comment]
Successfully applied on top of 5.11.4 and v5.12-rc3-3-g1a4431a5db2b

**Comment by graysky2** [comment]
Your new commit worked for me with that error, thanks.

**Pull request merged**
