### PR TITLE
Add MNATIVE_INTEL and MNATIVE AMD

### PR DESCRIPTION
**Pull request by sirlucjan**
Referring to the discussion in #63, I tried to solve the problem as follows. What do you think about this @graysky2?

Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

### CODE REVIEW

**Comment by sirlucjan** [comment]
If X86_CMOV is needed for AMD, I can fix that very quickly.

**Comment by graysky2** [comment]
Looks decent.  I do not have AMD hardware for testing.  We can only assume about the `X86_CMOV` setting or try to dig up information on it.  Do you have AMD hardware?

**Comment by sirlucjan** [comment]
No. I suggest adding just in case, since it was reported that Ryzen has such a flag.

**Comment by montjoie** [comment]
For me you need to split in two. Rename MNATIVE to MNATIVE_INTEL since it is what it mean to be. Then add MNATIVE_AMD.

**Comment by sirlucjan** [comment]
@graysky2 Should I do another rebase? If so, I will send it out on Monday.

**Comment by graysky2** [comment]
Where did we land on the `X86_CMOV` for AMD flag?

**Comment by sirlucjan** [comment]
It was mentioned earlier that Ryzen has one. Maybe it's worth giving it a try?

**Comment by graysky2** [comment]
It's include it for AMD since upstream has it for both K7 and K8.  Please rebase/fpush.

**Pull request closed without merging**
